### ISSUE TITLE
Updater does no longer work

### ISSUE THREAD

**Issue by a-schild** [dennis-eisen/CT_AutoUpdater#3]
The last update which did work was on the 4.December 2019.
All updates since then have not been detected/installed.

Perhaps a change in seafile does prevent from finding new releases?

**Comment by karl007** [comment]
It seems seafile changed the pag build process from "static" html to dynamic javascript. The html page only contains a basic structure and JS files and the real content (file list) is loaded with javascript from the browser. So it might be difficult to get the real URL of the zip file.

A solution may be the [Seafile API](https://download.seafile.com/published/web-api/home.md), but `All API calls must be authenticated with a valid Seafile API key.`, so we need a token from CT.

**Comment by karl007** [comment]
I find a solution and made a [PullRequest](https://github.com/dennis-eisen/CT_AutoUpdater/pull/5)
This fix and a optimized version for better updating and configuration is available in my [fork](https://github.com/karl007/CT_AutoUpdater)

**Comment by dennis-eisen** [comment]
@karl007 Thank you for helping me out. Unfortunately I did not have the time to solve the problem myself.

**Comment by a-schild** [comment]
Thanks
